os:
- linux
- osx
branches:
  only:
  - master
env:
- NODE_VERSION="8.4.0"
before_script:
- chmod +x ./scripts/travis-build.sh
script: "./scripts/travis-build.sh"
cache:
  yarn: true
  directories:
    - node_modules
